version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horoscope_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FORCE_SYNC=false
      - TIMEZONE=+05:30
      - CORS_ORIGINS=https://test.medi.lk , https://prediction.medi.lk
      - PLANET_HOUSE_API_URL="https://api.vedicastroapi.com/v3-json/horoscope/planets-in-houses"
      - MAHADASHA_API_URL="https://api.vedicastroapi.com/v3-json/dashas/maha-dasha"
      - ANTHARDASHA_API_URL="https://api.vedicastroapi.com/v3-json/dashas/antar-dasha"
      - LIFETIME_PREDICTION_API_URL="https://api.vedicastroapi.com/v3-json/horoscope/planet-report"
      - NAVANSHAKA_API_URL="https://api.vedicastroapi.com/v3-json/horoscope/divisional-charts"
      - ASCTROLOGIC_DATA_API_URL="https://api.vedicastroapi.com/v3-json/extended-horoscope/extended-kundli-details"
      - DAILY_PREDICTION_API_URL="https://api.vedicastroapi.com/v3-json/prediction/daily"
      - WEEKLY_PREDICTION_API_URL="https://api.vedicastroapi.com/v3-json/prediction/weekly"
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ACCESS_TOKEN_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN=7d
      - BCRYPT_ROUNDS=12
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - PAYHERE_MERCHANT_ID="4OVyImsVAsC4JBvq3iRdAf3LJ"
      - PAYHERE_MERCHANT_SECRET="4PYR3iBLDkN4fWkF5nayc04eU2YBKJ8Lv4ZE7Ed7Ysmz"
      - PAYHERE_SANDBOX=true
      - DB_SSL=false
    networks:
      - horoscope_network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  horoscope_network:
    driver: bridge
